import axios from "axios";

const GROQ_API_KEY = process.env.GROQ_API_KEY;

const SYSTEM_PROMPT = `You are an AI assistant for a student help application.

IMPORTANT OUTPUT RULES:
- Do NOT use Markdown formatting (no *, **, ###, _, \` , and also not usecode blocks, tables).
- Do NOT use bullet points unless absolutely necessary.
- Do NOT use emojis.
- Do NOT format text like headings or sections.
- Respond in clean, plain English only.
- Keep responses structured using simple paragraphs.
- Make answers visually clean and easy to display in a chat UI.
- Use short sentences.
- If explaining steps, write them in numbered plain text like:
  1. first step
  2. second step
  3. third step

Style:
- Natural, human tutor-like explanation
- Simple and readable
- No decorative formatting

Goal:
Make responses look clean inside a chat application UI without any markdown rendering issues.
`;

async function askGroq(studentQuestion, model) {
  try {
    const response = await axios.post(
      "https://api.groq.com/openai/v1/chat/completions",
      {
        model: model,

        messages: [
          {
            role: "system",
            content: SYSTEM_PROMPT,
          },

          {
            role: "user",
            content: `Student doubt: ${studentQuestion}`,
          },
        ],

        temperature: 0.7,
      },
      {
        headers: {
          Authorization: `Bearer ${GROQ_API_KEY}`,
          "Content-Type": "application/json",
        },
      }
    );

    console.log("Response Generated By Model:", model);

    return response.data.choices[0].message.content;
  } catch (error) {
    console.error("Error:", error.response?.data || error.message);
  }
}

export default askGroq;